import type { Linter } from 'eslint'
import antfu from '@antfu/eslint-config'
import jsonSchemaValidator from 'eslint-plugin-json-schema-validator'

const config: Promise<Linter.Config[]> = antfu(
	{
		plugins: {
			'json-schema-validator': jsonSchemaValidator,
		},
		pnpm: {
			sort: false,
		},
		rules: {
			'json-schema-validator/no-invalid': 'error',
		},
		settings: {
			'json-schema-validator': {
				cache: {
					path: 'node_modules/.cache/eslint/plugin-json-schema-validator',
				},
			},
		},
		stylistic: {
			indent: 'tab',
			overrides: {
				'style/quote-props': ['error', 'as-needed'],
			},
		},
		type: 'lib',
		typescript: true,
	},
	{
		files: ['pnpm-workspace.yaml'],
		rules: {
			'json-schema-validator/no-invalid': 'off', // temporary unitl v12.6 schema is published
			'pnpm/yaml-enforce-settings': ['error', {
				forbiddenFields: [
					'allowedDeprecatedVersions',
					'allowNonAppliedPatches',
					'allowUnusedPatches',
					'auditConfig',
					'auditLevel',
					'autoInstallPeers',
					'blockExoticSubdeps',
					'ca',
					'cacheDir',
					'cafile',
					'catalogs',
					'cert',
					'childConcurrency',
					'ci',
					'cleanupUnusedCatalogs',
					'color',
					'configDependencies',
					'confirmModulesPurge',
					'dangerouslyAllowAllBuilds',
					'dedupeInjectedDeps',
					'dedupePeerDependents',
					'deployAllFiles',
					'dlxCacheMaxAge',
					'embedReadme',
					'enableGlobalVirtualStore',
					'enableModulesDir',
					'engineStrict',
					'executionEnv',
					'extendNodePath',
					'failIfNoMatch',
					'fetchMinSpeedKiBps',
					'fetchRetries',
					'fetchRetryFactor',
					'fetchRetryMaxtimeout',
					'fetchRetryMintimeout',
					'fetchTimeout',
					'fetchWarnTimeoutMs',
					'forceLegacyDeploy',
					'frozenStore',
					'gitBranchLockfile',
					'gitChecks',
					'gitShallowHosts',
					'globalBinDir',
					'globalDir',
					'globalPnpmfile',
					'globalShims',
					'hoistingLimits',
					'hoistPattern',
					'hoistWorkspacePackages',
					'httpProxy',
					'httpsProxy',
					'ignoreCompatibilityDb',
					'ignoredBuiltDependencies',
					'ignoreDepScripts',
					'ignoredOptionalDependencies',
					'ignorePatchFailures',
					'ignorePnpmfile',
					'ignoreScripts',
					'ignoreWorkspaceCycles',
					'ignoreWorkspaceRootCheck',
					'includeWorkspaceRoot',
					'injectWorkspacePackages',
					'key',
					'linkWorkspacePackages',
					'localAddress',
					'lockfile',
					'lockfileIncludeTarballUrl',
					'loglevel',
					'managePackageManagerVersions',
					'maxsockets',
					'mergeGitBranchLockfilesBranchPattern',
					'minimumReleaseAge',
					'minimumReleaseAgeExclude',
					'minimumReleaseAgeIgnoreMissingTime',
					'minimumReleaseAgeStrict',
					'modulesCacheMaxAge',
					'modulesDir',
					'namedRegistries',
					'networkConcurrency',
					'neverBuiltDependencies',
					'nodeDownloadMirrors',
					'nodeExperimentalPackageMap',
					'nodeLinker',
					'nodePackageMapType',
					'nodeVersion',
					'noProxy',
					'npmPath',
					'npmrcAuthFile',
					'onlyBuiltDependencies',
					'onlyBuiltDependenciesFile',
					'optimisticRepeatInstall',
					'overrides',
					'packageConfigs',
					'packageExtensions',
					'packageImportMethod',
					'packageManagerStrict',
					'packageManagerStrictVersion',
					'patchedDependencies',
					'patchesDir',
					'peerDependencyRules',
					'peersSuffixMaxLength',
					'pipelineBase',
					'pipelines',
					'pmOnFail',
					'pnpmfile',
					'preferFrozenLockfile',
					'preferOffline',
					'preferSymlinkedExecutables',
					'preferWorkspacePackages',
					'provenance',
					'proxy',
					'publicHoistPattern',
					'publishBranch',
					'recursiveInstall',
					'registries',
					'registry',
					'registrySupportsTimeField',
					'reporter',
					'requiredScripts',
					'resolvePeersFromWorkspaceRoot',
					'runtime',
					'runtimeOnFail',
					'saveExact',
					'savePrefix',
					'saveWorkspaceProtocol',
					'scriptShell',
					'shamefullyHoist',
					'sharedWorkspaceLockfile',
					'shellEmulator',
					'sideEffectsCache',
					'sideEffectsCacheReadonly',
					'stateDir',
					'storeDir',
					'strictDepBuilds',
					'strictSsl',
					'strictStorePkgContentCheck',
					'supportedArchitectures',
					'symlink',
					'syncInjectedDepsAfterScripts',
					'tag',
					'tasks',
					'trustLockfile',
					'trustPolicy',
					'trustPolicyIgnoreAfter',
					'unsafePerm',
					'update',
					'updateConfig',
					'updateNotifier',
					'useBetaCli',
					'useNodeVersion',
					'useRunningStoreServer',
					'useStderr',
					'verifyDepsBeforeRun',
					'verifyStoreIntegrity',
					'versioning',
					'virtualStoreDir',
					'virtualStoreDirMaxLength',
					'virtualStoreOnly',
					'virtualStoreType',
					'workspaceConcurrency',
				],
				requiredFields: ['packages'],
				settings: {
					audit: { ignorePrune: true },
					autoDedupe: true,
					catalogMode: 'strict',
					catalogPrune: true,
					dedupeDirectDeps: true,
					dedupePeers: true,
					disallowWorkspaceCycles: true,
					enablePrePostScripts: false,
					hoist: false,
					minimumReleaseAgeExcludePrune: true,
					resolutionMode: 'lowest-direct',
					strictPeerDependencies: true,
					trustPolicyExcludePrune: true,
				},
			}],
		},
	},
	{
		files: ['package.json'],
		rules: {
			'jsonc/no-comments': ['error'],
		},
	},
	{
		files: [
			'.vscode/*.json',
		],
		rules: {
			'jsonc/comma-dangle': ['error', 'always-multiline'],
		},
	},
)
export default config
