packages: []

catalog:
  '@antfu/eslint-config': 6.5.1
  eslint: 9.39.1

catalogMode: strict

dedupeDirectDeps: true

hoist: false

ignorePatchFailures: false

minimumReleaseAge: 1440

packageManagerStrictVersion: true

resolutionMode: lowest-direct

strictDepBuilds: true

strictPeerDependencies: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - '@yarnpkg/libzip@3.2.2'
  - semver@5.7.2 || 6.3.1

verifyDepsBeforeRun: install
