packages: []

audit:
  ignorePrune: true

autoDedupe: true

catalog:
  '@antfu/eslint-config': 9.5.1
  eslint: 10.11.0
  eslint-plugin-json-schema-validator: ^6.3.1
catalogMode: strict

catalogPrune: true
dedupeDirectDeps: true
dedupePeers: true
disallowWorkspaceCycles: true
enablePrePostScripts: false
hoist: false
minimumReleaseAgeExcludePrune: true

nodeOptions: >-
  ${NODE_OPTIONS- }
  --no-addons
  --disable-proto=delete
  --force-context-aware
  --force-node-api-uncaught-exceptions-policy
  --frozen-intrinsics
  --no-global-search-paths
  --pending-deprecation
  --tls-min-v1.3

resolutionMode: lowest-direct
strictPeerDependencies: true
trustPolicyExcludePrune: true
