packages:
  - .

catalog:
  '@antfu/eslint-config': 6.4.1
  eslint: 9.39.1
  renovate: 42.39.1

catalogMode: prefer

cleanupUnusedCatalogs: true

dedupeDirectDeps: true

hoist: false

ignorePatchFailures: false

minimumReleaseAge: 1440

packageManagerStrictVersion: true

resolutionMode: lowest-direct

shellEmulator: true

strictPeerDependencies: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - '@yarnpkg/libzip@3.2.2'
  - semver@5.7.2 || 6.3.1
