name: CI

on:
  pull_request:
    branches: main
  push:
    branches: main

defaults:
  run:
    shell: sh

jobs:
  git-check:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/git/git/blob/master/ci/check-directional-formatting.bash
      # todo see if file will be in the index
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          sparse-checkout: '!/'
          sparse-checkout-cone-mode: false
      - run: |
          set -Cfu
          parent=$(exec git hash-object -t tree -- /dev/null)
          exec git diff-index --cached --check "$parent"
      - run: |
          set -Cfu
          exec git ls-files -eol

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          cache: pnpm
          node-version-file: .nvmrc
      - run: exec pnpm install
      - run: exec pnpm run test
