on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
permissions: { }
jobs:
  git-check:
    permissions:
      contents: read
    uses: mestriga-org/github-workflows/.github/workflows/git-check.yml@bc679db473646808e8af8ed0a0e59754adb75f57 # main
  pnpm-run-lint:
    permissions:
      contents: read
    uses: mestriga-org/github-workflows/.github/workflows/pnpm-run-lint.yml@bc679db473646808e8af8ed0a0e59754adb75f57 # main
  renovate-preset-validate:
    permissions:
      contents: read
    uses: mestriga-org/github-workflows/.github/workflows/renovate-preset-validate.yml@bc679db473646808e8af8ed0a0e59754adb75f57 # main
