on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
permissions: { }
jobs:
  git-check:
    permissions:
      contents: read
    uses: mestriga-org/github-workflows/.github/workflows/git-check.yml@41d1441915f2dc56e0da252916a0ec73ed203e03 # main
  pnpm-run-lint:
    permissions:
      contents: read
    uses: mestriga-org/github-workflows/.github/workflows/pnpm-run-lint.yml@41d1441915f2dc56e0da252916a0ec73ed203e03 # main
  renovate-preset-validate:
    permissions:
      contents: read
    uses: mestriga-org/github-workflows/.github/workflows/renovate-preset-validate.yml@41d1441915f2dc56e0da252916a0ec73ed203e03 # main
