name: CI

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          cache: pnpm
          node-version-file: .nvmrc
      - run: pnpm install
      - run: pnpm run lint
