on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
defaults:
  run:
    shell: bash
env:
  POSIXLY_CORRECT: y
permissions: { }
jobs:
  renovate-config-validate:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
