on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
defaults:
  run:
    shell: bash
env:
  POSIXLY_CORRECT: y
permissions: { }
jobs:
  renovate-config-validate:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false
          set-safe-directory: false
      - uses: docker://ghcr.io/renovatebot/renovate:42
        with:
          entrypoint: renovate-config-validator
